/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Microsoft
 */
public class GUI_AdminPanel_DataKelas extends javax.swing.JFrame {

    /**
     * Creates new form GUI_AdminPanel
     */
    public GUI_AdminPanel_DataKelas() {
        initComponents();
        mapelcbfilldata();
        tentorcbfilldata();
        DisplayTableKelasTentor();
        DisplayTableKelasSiswa();
    }
    
    public JButton getjHome() {

        return jHome;
    }

    public void setjHome(JButton jHome) {
        this.jHome = jHome;
    }

    public JButton getjKelas() {
        return jKelas;
    }

    public void setjKelas(JButton jKelas) {
        this.jKelas = jKelas;
    }

    public JButton getjMatakuliah() {
        return jMatakuliah;
    }

    public void setjMatakuliah(JButton jMatakuliah) {
        this.jMatakuliah = jMatakuliah;
    }

    public JButton getjSiswa() {
        return jSiswa;
    }

    public void setjSiswa(JButton jSiswa) {
        this.jSiswa = jSiswa;
    }

    public JButton getjTentor() {
        return jTentor;
    }

    public JButton getjLogout() {
        return jLogout;
    }

    public void setjLogout(JButton jLogout) {
        this.jLogout = jLogout;
    }

    public JButton getJbhapus() {
        return jbhapus;
    }

    public void setJbhapus(JButton jbhapus) {
        this.jbhapus = jbhapus;
    }

    public JButton getJbtambah() {
        return jbtambah;
    }

    public void setJbtambah(JButton jbtambah) {
        this.jbtambah = jbtambah;
    }

    public JButton getJbupdate() {
        return jbupdate;
    }

    public void setJbupdate(JButton jbupdate) {
        this.jbupdate = jbupdate;
    }

    public JComboBox<String> getJcbjam() {
        return jcbjam;
    }

    public void setJcbjam(JComboBox<String> jcbjam) {
        this.jcbjam = jcbjam;
    }

    public JComboBox<String> getJcbmapel() {
        return jcbmapel;
    }

    public void setJcbmapel(JComboBox<String> jcbmapel) {
        this.jcbmapel = jcbmapel;
    }

    public JComboBox<String> getJcbtentor() {
        return jcbtentor;
    }

    public void setJcbtentor(JComboBox<String> jcbtentor) {
        this.jcbtentor = jcbtentor;
    }

    public JTextField getJtfNamakelas() {
        return jtfNamakelas;
    }

    public void setJtfNamakelas(JTextField jtfNamakelas) {
        this.jtfNamakelas = jtfNamakelas;
    }

    public JTextField getJtfkodekelas() {
        return jtfkodekelas;
    }

    public void setJtfkodekelas(JTextField jtfkodekelas) {
        this.jtfkodekelas = jtfkodekelas;
    }    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLogout = new javax.swing.JButton();
        jSiswa = new javax.swing.JButton();
        jTentor = new javax.swing.JButton();
        jKelas = new javax.swing.JButton();
        jMatakuliah = new javax.swing.JButton();
        jHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtambah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        jtfkodekelas = new javax.swing.JTextField();
        jtfNamakelas = new javax.swing.JTextField();
        jcbjam = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jcbtentor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcbmapel = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablekelastentor = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtablekelassiswa = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(58, 83, 155));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN //");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E - LEARNING");

        jLogout.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLogout.setText("LOGOUT");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });

        jSiswa.setBackground(new java.awt.Color(58, 83, 155));
        jSiswa.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jSiswa.setForeground(new java.awt.Color(255, 255, 255));
        jSiswa.setText("DATA SISWA");
        jSiswa.setBorder(null);
        jSiswa.setBorderPainted(false);
        jSiswa.setContentAreaFilled(false);
        jSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSiswaActionPerformed(evt);
            }
        });

        jTentor.setBackground(new java.awt.Color(58, 83, 155));
        jTentor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jTentor.setForeground(new java.awt.Color(255, 255, 255));
        jTentor.setText("DATA TENTOR");
        jTentor.setBorder(null);
        jTentor.setContentAreaFilled(false);
        jTentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTentorActionPerformed(evt);
            }
        });

        jKelas.setBackground(new java.awt.Color(58, 83, 155));
        jKelas.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jKelas.setForeground(new java.awt.Color(255, 255, 255));
        jKelas.setText("DATA KELAS");
        jKelas.setBorder(null);
        jKelas.setBorderPainted(false);
        jKelas.setContentAreaFilled(false);
        jKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKelasActionPerformed(evt);
            }
        });

        jMatakuliah.setBackground(new java.awt.Color(58, 83, 155));
        jMatakuliah.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jMatakuliah.setForeground(new java.awt.Color(255, 255, 255));
        jMatakuliah.setText("DATA MATA KULIAH");
        jMatakuliah.setBorder(null);
        jMatakuliah.setContentAreaFilled(false);
        jMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatakuliahActionPerformed(evt);
            }
        });

        jHome.setBackground(new java.awt.Color(58, 83, 155));
        jHome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jHome.setForeground(new java.awt.Color(255, 255, 255));
        jHome.setText("HOME");
        jHome.setBorder(null);
        jHome.setBorderPainted(false);
        jHome.setContentAreaFilled(false);
        jHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLogout)
                    .addComponent(jKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMatakuliah)
                            .addComponent(jTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHome, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel2)
                    .addContainerGap(131, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel3)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jHome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTentor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLogout)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel2)
                    .addContainerGap(520, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jLabel3)
                    .addContainerGap(471, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN DATA KELAS // E - LEARNING");

        jPanel3.setBackground(new java.awt.Color(34, 49, 63));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode Kelas");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Kelas");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mata Pelajaran");

        jbtambah.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jbtambah.setText("TAMBAH");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });

        jbhapus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jbhapus.setText("HAPUS");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });

        jbupdate.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jbupdate.setText("UPDATE");

        jcbjam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.00", "11.00", "14.00" }));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jam");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tentor");

        jcbmapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmapelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfkodekelas, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jtfNamakelas)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbtentor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfkodekelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfNamakelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jcbmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jcbjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtentor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addComponent(jbtambah)
                .addGap(18, 18, 18)
                .addComponent(jbhapus)
                .addGap(18, 18, 18)
                .addComponent(jbupdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtablekelastentor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Kelas", "Tentor ID"
            }
        ));
        jScrollPane3.setViewportView(jtablekelastentor);

        jtablekelassiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Kelas", "NIM"
            }
        ));
        jScrollPane4.setViewportView(jtablekelassiswa);
        if (jtablekelassiswa.getColumnModel().getColumnCount() > 0) {
            jtablekelassiswa.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KELAS - TENTOR");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KELAS - STUDENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSiswaActionPerformed

    private void jTentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTentorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTentorActionPerformed

    private void jKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKelasActionPerformed

    private void jMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatakuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMatakuliahActionPerformed

    private void jHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHomeActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jcbmapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbmapelActionPerformed
     public void addActionListener(ActionListener e){
        jSiswa.addActionListener(e);
        jTentor.addActionListener(e);
        jKelas.addActionListener(e);
        jMatakuliah.addActionListener(e);
        jHome.addActionListener(e);
        jLogout.addActionListener(e);
        jbtambah.addActionListener(e);
        jbhapus.addActionListener(e);
        jbupdate.addActionListener(e);
    }
     
    public void addMouseAdapter(MouseAdapter ma){
        jtablekelastentor.addMouseListener(ma);
        jtablekelassiswa.addMouseListener(ma);
    }
    
    public JTable getJtablekelassiswa() {
        return jtablekelassiswa;
    }

    public void setJtablekelassiswa(DefaultTableModel x) {
        jtablekelassiswa.setModel(x);
    }

    public int getselectedkelassiswa(){
        return jtablekelassiswa.getSelectedRow();
    }
    
    public JTable getJtablekelastentor() {
        return jtablekelastentor;
    }

    public void setJtablekelastentor(DefaultTableModel x) {
        jtablekelastentor.setModel(x);
    }

    public int getselectedkelastentor(){
        return jtablekelastentor.getSelectedRow();
    }

    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
     
     public void mapelcbfilldata(){
         try{
             Class.forName("com.mysql.jdbc.Driver");
             String databaseURL = "jdbc:mysql://localhost:3306/db_elearning";
             Connection con = DriverManager.getConnection(databaseURL,"root","");
             Statement stat = con.createStatement();
             String selectQuery = "select namamapel from matapelajaran";
             ResultSet rs = stat.executeQuery(selectQuery);
             while(rs.next()){
                 jcbmapel.addItem(rs.getString("namamapel"));
             }
         }
         catch(Exception e){
             System.out.println(e);
         }
     }
     
     public void tentorcbfilldata(){
         try{
             Class.forName("com.mysql.jdbc.Driver");
             String databaseURL = "jdbc:mysql://localhost:3306/db_elearning";
             Connection con = DriverManager.getConnection(databaseURL,"root","");
             Statement stat = con.createStatement();
             String selectQuery = "select Nama from tentortable";
             ResultSet rs = stat.executeQuery(selectQuery);
             while(rs.next()){
                 jcbtentor.addItem(rs.getString("Nama"));
             }
         }
         catch(Exception e){
             System.out.println(e);
         }
     }
     
     public void DisplayTableKelasTentor(){
         try{
             Class.forName("com.mysql.jdbc.Driver");
             String databaseURL = "jdbc:mysql://localhost:3306/db_elearning";
             Connection con = DriverManager.getConnection(databaseURL,"root","");
             String query = "Select kodekelas,tentor_id from kelas";
             Statement S = con.createStatement();
             ResultSet R = S.executeQuery(query);
             DefaultTableModel table = new DefaultTableModel(new String[]{
                "Kode Kelas", 
                "Tentor ID"
            }, 0);
             while(R.next()){
                 table.addRow(new Object[]{R.getString("kodekelas"),R.getString("tentor_id"),});
             }
             jtablekelastentor.setModel(table);
         }catch(Exception e){
             //
         }
     }
     
     public void DisplayTableKelasSiswa(){
         try{
             Class.forName("com.mysql.jdbc.Driver");
             String databaseURL = "jdbc:mysql://localhost:3306/db_elearning";
             Connection con = DriverManager.getConnection(databaseURL,"root","");
             String query = "Select * from kelas_student";
             Statement S = con.createStatement();
             ResultSet R = S.executeQuery(query);
             DefaultTableModel table = new DefaultTableModel(new String[]{
                "Kode Kelas", 
                "NIM"
            }, 0);
             while(R.next()){
                 table.addRow(new Object[]{R.getString("kodekelas"),R.getString("nim"),});
             }
             jtablekelassiswa.setModel(table);
         }catch(Exception e){
             //
         }
     }
     
     public void resetview(){
         jtfkodekelas.setText("");
         jtfNamakelas.setText("");
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jHome;
    private javax.swing.JButton jKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLogout;
    private javax.swing.JButton jMatakuliah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jSiswa;
    private javax.swing.JButton jTentor;
    private javax.swing.JButton jbhapus;
    private javax.swing.JButton jbtambah;
    private javax.swing.JButton jbupdate;
    private javax.swing.JComboBox<String> jcbjam;
    private javax.swing.JComboBox<String> jcbmapel;
    private javax.swing.JComboBox<String> jcbtentor;
    private javax.swing.JTable jtablekelassiswa;
    private javax.swing.JTable jtablekelastentor;
    private javax.swing.JTextField jtfNamakelas;
    private javax.swing.JTextField jtfkodekelas;
    // End of variables declaration//GEN-END:variables
}
